export const TABS = [
  { label: "Business, Goods & State Info", key: "business" },
  { label: "People (Promoters, Signatory & Rep)", key: "people" },
  { label: "Place of Business", key: "place" },
  { label: "Aadhaar & Verification", key: "verify" },
];

export const STORAGE_KEY = "gst_reg_form_data";

export const INITIAL_STATE = {
  legal_name: "", pan: "", pan_date: "",
  "Constitution of Business": "", trade_name: "",
  state: "Gujarat", District: "",
  toggle: false, toggle_1: false, radioBlocks: null, text: null,
  reason: "", commencement_date: "", commencement_date_1: "",
  existing_registrations_list: [], file: null,
  proof_of_constitution: "", constitution_document: null,
  district: null, "Reason to obtain registration": null,
  name_first: "", name_middle: "", name_last: "",
  father_first: "", father_middle: "", father_last: "",
  dob: "", mobile: "", email: "", telephone: "",
  radiogroup_1: null, designation: "", din: "",
  toggle_2: false, pan_proprietor: "", passport: null,
  aadhaar: null, country: "IND",
  pin_code: "", state_res: "", district_res: "", city_res: "",
  locality: "", road_street_res: "", premises_name: "",
  building_no_res: "", floor_no_res: "", landmark_res: "",
  photo: null, "Also Authorized Signatory": false,
  name_first_2: "", name_middle_2: "", name_last_2: "",
  father_first_2: "", father_middle_2: "", father_last_2: "",
  dob_2: "", mobile_2: "", email_2: "", telephone_2: null,
  radiogroup_1_2: null, designation_2: "", din_2: "",
  toggle_2_2: false, pan_proprietor_2: "", passport_2: null,
  aadhaar_2: null, country_2: "IND",
  pin_code_2: "", state_res_2: "", district_res_2: "", city_res_2: "",
  locality_2: "", road_street_res_2: "", premises_name_2: "",
  building_no_res_2: "", floor_no_res_2: "", landmark_res_2: "",
  photo_2: null, "Also Authorized Signatory_2": false,
  is_primary: false,
  as_name_first: "", as_name_middle: "", as_name_last: "",
  as_father_first: "", as_father_middle: "", as_father_last: "",
  as_dob: "", as_mobile: "", as_email: "", as_telephone: null,
  radiogroup_1: null, as_designation: "", as_din: "", as_pan: "",
  toggle_3: false, as_passport: null, as_aadhaar: null,
  as_country: "IND", as_pin: "",
  as_state: null, as_district: null, as_city: null,
  as_locality: null, as_road: null, as_premises: null,
  as_bno: null, as_floor: null, as_landmark: null,
  as_proof_type: "", as_proof_file: null, as_photo: null,
  toggle_4: false, radiogroup_2: null, enrolment_id: "",
  rep_name_first: "", rep_name_middle: "", rep_name_last: "",
  rep_designation: "", rep_mobile: "", rep_email: "",
  rep_pan: "", rep_aadhaar: null, rep_telephone: "", rep_fax: null,
  ppb_pin: "", ppb_state: "Gujarat", ppb_district: "",
  ppb_city: null, ppb_locality: "", ppb_road: "",
  ppb_premises: "", ppb_bno: "", ppb_floor: "", ppb_landmark: "",
  ppb_lat: null, ppb_long: null,
  sector_circle: "", center_commissionerate: "",
  center_division: "", center_range: "",
  ppb_email: null, ppb_office_tel: "", ppb_mobile: null, ppb_fax: null,
  ppb_possession_type: "", ppb_proof_doc: "", ppb_file: null,
  ba_bonded_warehouse: false, ba_eou: false, ba_export: false,
  ba_factory: false, ba_import: false, ba_services: false,
  ba_leasing: false, ba_office: false, ba_recipient: false,
  ba_retail: false, ba_warehouse: false, ba_wholesale: false,
  ba_works_contract: false, ba_others: false, ba_others_specify: null,
  toggle_5: false, apb_count: "", apb_pin: "", apb_state: "Gujarat",
  apb_district: null, apb_city: null, apb_locality: "", apb_road: "",
  apb_premises: "", apb_bno: "", apb_floor: "", apb_landmark: "",
  apb_lat: null, apb_long: null, apb_email: "", apb_office_tel: "",
  apb_mobile: "", apb_fax: null, apb_possession_type: "",
  apb_proof_doc: "", apb_file: null,
  apb_bonded_warehouse: false, apb_eou: false, apb_export: false,
  apb_factory: false, apb_import: false, apb_services: false,
  apb_leasing: false, apb_office: false, apb_recipient: false,
  apb_retail: false, apb_warehouse: false, apb_wholesale: false,
  apb_works_contract: false, apb_others: false, apb_others_specify: null,
  hsn_search: "", commodities_list: [],
  sac_search: "", services_list: [],
  nature_of_possession_ppb: "", electricity_board: "",
  consumer_number: "", prof_tax_ec: "", prof_tax_rc: "",
  state_excise_lic: "", excise_person_name: "",
  opt_for_aadhaar: false,
  declaration: false, signatory: "", place: "",
  designation_ver: "Proprietor", date_ver: "",
  promoter_ids: [""], // Dynamic promoter tracking
};
